terminate called after throwing an instance of 'std::bad_alloc'
  what():  St9bad_alloc
terminate called after throwing an instance of 'std::bad_alloc'
  what():  St9bad_alloc
<Nov 26 23:42:05.914691> BE_MPI (ERROR): The error message in the job record is as follows:
<Nov 26 23:42:05.914777> BE_MPI (ERROR):   "killed with signal 6"
